travis:
  secure:
    BINSTAR_TOKEN: NZiSH54v6/aiyh1oeUc4KpER6Cw2dzJVw+O+xlJ2qZjZVZoj+Ly83TbR5OgYU48+tfNoY8Bf2YOaTeKms35GG8ZOL5eZL4LzZCOE9szKnuhRzhcPFmKZkWNwQCfiGrmRoKuqdbBZ4PTm7YR6tgegr6YWqvyiUv7jCJY6lq0s9Kn6KRZ/gOD8SYgECu5QXk2c2HtZjhk01Wr/h07b3gjx89OBdsmVnVRrrNAols+JicrvjcDIW7fW0qUu/8JwOOSjM+qhIf/SlhhzuBbGbpwdrCZJGUubhxa/tQZl9i/6hKuD6uxHbowGYGXWnWZtbXGRJdOmijRNrLy1sfwKnRm2y4cMMuHxr/OgVniSJEUz28k54O/qKQejzPEe4O7IBru65+THsSMtNaNelT9n69ntoRVtuUegrZ6j6lxTWQE7swYTCmF+Uo6TVdM/aclKLsFfEIxnZG1OLfDJTeQbFf6Gl0keV9AAybMPVQd7DUqk8VRstruirktEhiool2MdvSjo8qwlu0+mck9aU2Jz6QD2d7nU15lYKZwgPUGFgULKoTUxy1p9HtDfYhUCe2uhW7Z8jbwrzXxpj+Di/r/Dr9ikfv3ed5mk/5NQOe78GUJ91/Cd2Soq/1FXkU+b5XmWFoA6tuhCTR36DChr4yVkloCQRTFtJTIeWYCgest9Zt/KJbk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
